services:
  - type: web
    name: srt-factcheck-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: EASYOCR_LANGS
        sync: false
